# Puerto del servidor Spring Boot
server.port=8081

# Configuración de Conexión a PostgreSQL ACA CAMBIAR PARA CASOS DE DOCKER
spring.datasource.url=jdbc:postgresql://localhost:5432/albalanadb
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/albalanadb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# ddl-auto opciones:
#   update: crea/actualiza tablas sin borrar datos existentes (recomendado en desarrollo)
#   create-drop: crea las tablas al iniciar y las borra al cerrar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
# Revela la causa exacta de la falla de autenticación en Spring Security
logging.level.org.springframework.security=DEBUG

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Configuración de JWT
jwt.secret=1s8B2fq2Hmt9BzVlNrSdAU9X0t0dN5/clAIA7vAjq2c=
jwt.expiration-ms=86400000


