# Puerto del servidor Spring Boot
server.port=8081

# Configuración de Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/albalanadb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# ddl-auto opciones:
#   update: crea/actualiza tablas sin borrar datos existentes (recomendado en desarrollo)
#   create-drop: crea las tablas al iniciar y las borra al cerrar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false